### ISSUE TITLE
fatal error: too many errors emitted, stopping now [-ferror-limit=]

### ISSUE THREAD

**Issue by mattdell** [m0g/node-libraw#2]
When I run `npm install --save libraw` I get the following..

```
mdell~/W/R/my-project> npm install --save libraw

> libraw@0.1.3 install /Users/mdell/Work/Repos/my-project/node_modules/libraw
> node-gyp rebuild

  CXX(target) Release/obj.target/libraw/vendor/LibRaw/internal/dcraw_common.o
../vendor/LibRaw/internal/dcraw_common.cpp:560:54: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
  while (!reset && vbits < nbits && (c = fgetc(ifp)) != EOF && !(reset = zero_after_ff && c == 0x...
                                     ~~~~~~~~~~~~~~  ^  ~~~
../vendor/LibRaw/internal/dcraw_common.cpp:694:19: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
  for (i = 540; i < sizeof test - 1; i++)
                ~ ^ ~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:781:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:871:5: error: cannot use 'throw' with exceptions disabled
    throw LIBRAW_EXCEPTION_IO_CORRUPT;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:960:5: error: cannot use 'throw' with exceptions disabled
    throw LIBRAW_EXCEPTION_IO_CORRUPT;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:998:11: error: cannot use 'throw' with exceptions disabled
          throw LIBRAW_EXCEPTION_IO_CORRUPT;
          ^
../vendor/LibRaw/internal/dcraw_common.cpp:1013:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:1096:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:1181:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:1205:7: warning: comparison of integers of different signs:
      'int' and 'unsigned int' [-Wsign-compare]
      FORC(tiff_samples)
      ^~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/defines.h:96:33: note: expanded from macro 'FORC'
#define FORC(cnt) for (c = 0; c < cnt; c++)
                              ~ ^ ~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1316:7: error: cannot use 'throw' with exceptions disabled
      throw;
      ^
../vendor/LibRaw/internal/dcraw_common.cpp:1279:33: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
        for (jrow = 0; jrow + 7 < jh.high; jrow += 8)
                       ~~~~~~~~ ^ ~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1284:35: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
          for (jcol = 0; jcol + 7 < jh.wide; jcol += 8)
                         ~~~~~~~~ ^ ~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1297:41: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
        for (row = col = jrow = 0; jrow < jh.high; jrow++)
                                   ~~~~ ^ ~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1358:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:1347:27: warning: comparison of integers of different signs:
      'int' and 'unsigned int' [-Wsign-compare]
        for (col = 0; col < raw_width * tiff_samples; col++)
                      ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1414:9: warning: unused variable 'red' [-Wunused-variable]
    int red = fread(buf, 1, bufsize, ifp);
        ^
../vendor/LibRaw/internal/dcraw_common.cpp:1521:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:1605:17: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
  for (i = 0; i < sizeof table / sizeof *table; i++)
              ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1623:22: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
  for (nz = i = 0; i < sizeof tail; i++)
                   ~ ^ ~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1648:17: warning: comparison of integers of different signs:
      'int' and 'unsigned int' [-Wsign-compare]
  for (i = 0; i < thumb_length; i++)
              ~ ^ ~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1666:17: warning: comparison of integers of different signs:
      'int' and 'unsigned int' [-Wsign-compare]
  for (i = 0; i < thumb_length; i++)
              ~ ^ ~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1739:21: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
      for (c = 0; c < nc; c += 2)
                  ~ ^ ~~
../vendor/LibRaw/internal/dcraw_common.cpp:1754:23: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
        for (c = 0; c < nc; c += 2)
                    ~ ^ ~~
../vendor/LibRaw/internal/dcraw_common.cpp:1768:25: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
          for (c = 0; c < nc; c += 2)
                      ~ ^ ~~
../vendor/LibRaw/internal/dcraw_common.cpp:1773:23: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
        for (c = 0; c < nc; c += 2)
                    ~ ^ ~~
../vendor/LibRaw/internal/dcraw_common.cpp:1944:54: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
            for (row = (qr ? ph1.split_row : 0); row < (qr ? raw_height : ph1.split_row); row++)
                                                 ~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1949:56: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
              for (col = (qc ? ph1.split_col : 0); col < (qc ? raw_width : ph1.split_col); col++)
                                                   ~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1985:27: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
            i = qmult[row >= ph1.split_row][col >= ph1.split_col] * RAW(row, col);
                      ~~~ ^  ~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:1985:49: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
            i = qmult[row >= ph1.split_row][col >= ph1.split_col] * RAW(row, col);
                                            ~~~ ^  ~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:2014:54: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
            for (row = (qr ? ph1.split_row : 0); row < (qr ? raw_height : ph1.split_row); row++)
                                                 ~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:2019:56: warning: comparison of integers of different signs:
      'unsigned int' and 'int' [-Wsign-compare]
              for (col = (qc ? ph1.split_col : 0); col < (qc ? raw_width : ph1.split_col); col++)
                                                   ~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:2166:5: error: cannot use 'throw' with exceptions disabled
    throw LIBRAW_EXCEPTION_IO_CORRUPT;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:2254:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:2339:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:2289:23: warning: comparison of integers of different signs:
      'int' and 'unsigned int' [-Wsign-compare]
        for (s = 0; s < tiff_samples * 2; s += 2)
                    ~ ^ ~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:2314:11: warning: comparison of integers of different signs:
      'int' and 'unsigned int' [-Wsign-compare]
          FORC(tiff_samples)
          ^~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/defines.h:96:33: note: expanded from macro 'FORC'
#define FORC(cnt) for (c = 0; c < cnt; c++)
                              ~ ^ ~~~
../vendor/LibRaw/internal/dcraw_common.cpp:2388:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:2479:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:2662:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:3055:21: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
  for (s = i = 0; i < sizeof src; i += 2)
                  ~ ^ ~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:3061:17: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
  for (i = 0; i < sizeof(buf) / sizeof(short); i++)
              ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:3075:21: warning: comparison of integers of different signs:
      'int' and 'unsigned long' [-Wsign-compare]
      for (i = 0; i < sizeof(buf[0]) / sizeof(short); i++)
                  ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../vendor/LibRaw/internal/dcraw_common.cpp:3430:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:3473:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
../vendor/LibRaw/internal/dcraw_common.cpp:3515:5: error: cannot use 'throw' with exceptions disabled
    throw;
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
27 warnings and 20 errors generated.
make: *** [Release/obj.target/libraw/vendor/LibRaw/internal/dcraw_common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mdell/.nvm-fish/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Users/mdell/.nvm-fish/v5.1.0/bin/node" "/Users/mdell/.nvm-fish/v5.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mdell/Work/Repos/my-project/node_modules/libraw
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPACKAGEJSON my-project@0.0.1 No description
npm WARN EPACKAGEJSON my-project@0.0.1 No repository field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/mdell/.nvm-fish/v5.1.0/bin/node" "/Users/mdell/.nvm-fish/v5.1.0/bin/npm" "install" "--save" "libraw"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! libraw@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libraw@0.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libraw package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libraw
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mdell/Work/Repos/my-project/npm-debug.log
```

Any ideas? This is on node version 5.1.0.

**Comment by m0g** [comment]
Hey, are you on OSX?

For now node-libraw is not supported on OSX

**Comment by mattdell** [comment]
Yes I am. That would explain it. 😔

**Comment by m0g** [comment]
Ideally yes, the only problem being that I don't have access to an apple computer

**Comment by mattdell** [comment]
Turns out I do. Could I help in some way?

I'm a web developer so this is sort of new territory for me but wouldn't mind having a crack. Do you know roughly what would need to be done to make this work for OSX?

**Comment by m0g** [comment]
Yes you can.

Basically in case you didn't, `node-libraw` is a binding for the `libraw` c++ library.

In the code base there are a couple `*.gyp` files that are responsible for compiling `libraw` on the host system. Those files would need to be modified in order for `libraw` to compile.

The binding files:

* https://github.com/m0g/node-libraw/blob/master/binding.gyp
* https://github.com/m0g/node-libraw/blob/master/vendor/libraw.gyp

Libraw documentation: http://www.libraw.org/docs/Install-LibRaw-eng.html

**Comment by m0g** [comment]
OSX support is here
