### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by mmick66** [m0g/node-libraw#6]
I used to work with this library but some of my old projects no longer compile as the library is throwing an error:

```bash
4 warnings and 4 errors generated.
make: *** [Release/obj.target/node_libraw/node_libraw.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/michaelmichailidis/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:190:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/Users/michaelmichailidis/.nvm/versions/node/v12.6.0/bin/node" "/Users/michaelmichailidis/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/michaelmichailidis/Projects/manscupianconverter/node_modules/libraw
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libraw@0.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libraw@0.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelmichailidis/.npm/_logs/2019-11-03T09_17_23_766Z-debug.log
```

**Comment by m0g** [comment]
Hello @mmick66 before running `npm install`, have you tried to update the git submodule?

```bash
git submodule init
git submodule update
```

**Comment by mmick66** [comment]
Yep, same problem...

```bash
../node_libraw.cc:28:53: error: no matching member function for call to 'ToString'
    v8::String::Utf8Value filenameFromArgs(info[0]->ToString());
                                           ~~~~~~~~~^~~~~~~~
/Users/mmick66/Library/Caches/node-gyp/12.6.0/include/node/v8.h:2528:44: note: candidate function not viable: requires single
      argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
```

I am on a:
**MacBook Pro (Retina, 15-inch, Late 2013)
macOS Catalina v.10.15.1**

Any thoughts?

**Comment by m0g** [comment]
Unfortunately I do not use OSX so I can't really help you

**Comment by mmick66** [comment]
Thing is, it used to work. I do not know what changed in the OS since the last few updates...

**Comment by nowaythatworked** [comment]
I just stumbled upon this, @mmick66 did you find any solution to this problem?
